export class IncomeTypes {
  public static incomeTypes = ['INDEPENDENT ACTIVITIES', 'INTELLECTUAL PROPERTY-RIGHTS', 'AGRICULTURAL ACTIVITIES', 'SILVICULTURE',
    'PISCICULTURE', 'TRANSFER OF THE USER OF THE GOODS FOR TOURISM PURPOSES', 'SALARY'];
}
